### ISSUE TITLE
List of things to be added in PHP lint rewrite

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#138]
I'm only talking about parsing each PHP file. Build-related problems including missing plugin.yml, missing stub, etc. aren't included.

* PHP problems
  * syntax errors
  * dead code. We've got enough `return true; break;`, whichever idiot started it on day one.
  * PSR-0 inconsistency
* Bad practice
  * Declaration of symbols in the global namespace (esp. constants)
  * Use of PHP controls that aren't acceptable in PocketMine
    * `echo` -> logger
    * `die`/`exit` -> disablePlugin
    * `eval` -> dangerous
* PocketMine problems
  * Post-disable compatibility
    * extends Command but does not implement PluginIdentifiableCommand
    * extends Task but does not extend PluginTask
  * Not declaring required extensions
    * Particularly, scan for common functions like `mb_strlen`, `imagecreatefrompng`, etc.

In addition, allow disabling certain lint.

**Comment by JaxkDev** [comment]
Majority of list is now implemented / redundant by PHPStan

Notably the PocketMine problems are basically all thats left.

**Comment by SOF3** [comment]
I am of the opinion that CI is best moved to GitHub actions and stop maintaining on Poggit's side, so let's close this. I would personally prefer a roadmap of gradually migrating different features from Poggit to GitHub until Poggit is just a plugin list, then eventually someone can rewrite a UI that eliminates the Poggit UI.
